package com.spacecomplexity.longboilife.game.utils;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.math.Vector3;
import com.spacecomplexity.longboilife.game.building.Building;
import com.spacecomplexity.longboilife.game.building.BuildingCategory;
import com.spacecomplexity.longboilife.game.building.BuildingType;
import com.spacecomplexity.longboilife.game.globals.Constants;
import com.spacecomplexity.longboilife.game.globals.GameState;
import com.spacecomplexity.longboilife.game.globals.MainCamera;
import com.spacecomplexity.longboilife.game.world.World;
import java.util.*;

/** A class used for game utilities. */
public class GameUtils {

  /**
   * Get the current position of the mouse relative to the world grid.
   *
   * @param world the world reference for size.
   * @return the grid index at the current mouse position.
   */
  public static Vector2Int getMouseOnGrid(World world) {
    // Get the position of mouse in world coordinates
    Vector3 mouse = new Vector3(Gdx.input.getX(), Gdx.input.getY(), 0);
    MainCamera.camera().getCamera().unproject(mouse);

    // Divide these by the cell size (as the world starts at (0, 0))
    float cellSize = Constants.TILE_SIZE * GameState.getState().scaleFactor;
    return new Vector2Int(
        Math.max(0, Math.min((int) (mouse.x / cellSize), world.getWidth() - 1)),
        Math.max(0, Math.min((int) (mouse.y / cellSize), world.getHeight() - 1)));
  }

  /** Calculate and set scaling factors using the window size. */
  public static void calculateScaling() {
    int screenHeight = Gdx.graphics.getHeight();

    // If height is 0 then the window is minimised so don't bother calculating as this could cause
    // unintended behaviour with scaling at 0
    if (screenHeight == 0) return;

    // Calculate scale factor based on screen height linearly using constant
    GameState.getState().scaleFactor = screenHeight / (float) Constants.SCALING_1_HEIGHT;
    // Calculate UI scale factor based on screen height using scaling map
    GameState.getState().uiScaleFactor =
        Constants.UI_SCALING_MAP.floorEntry(screenHeight).getValue();
  }

  /**
   * Update satisfaction score.
   *
   * <p>Satisfaction is generated by multiplying a set of modifiers, all of which are between 0 and
   * 1. distanceModifier is calculated based on the average shortest distance to buildings in other
   * categories from the average accommodation building. buildingCountModifier is calculated based
   * on the building count - fewer buildings means a lower modifier. buildingProportionModifier is
   * calculated based on the difference in number of buildings in each category.
   * emptyCategoryModifier is calculated by working out the proportion of categories that haven't
   * been placed yet.
   *
   * @param world the world reference for buildings.
   */
  public static void updateSatisfactionScore(World world) {
    // >>>> CHANGED CODE START <<<<
    GameState gameState = GameState.getState();

    float newSatisfactionScore;

    float distanceModifier = 0;
    float buildingCountModifier = 1;
    float buildingProportionModifier = 1;
    float emptyCategoryModifier = 1;

    Vector<Building> buildings = world.getBuildings();

    // Map containing buildings split into categories
    HashMap<BuildingCategory, Vector<Building>> categorisedBuildings = new HashMap<>();

    // Get categories of buildings which will affect satisfaction score
    Set<BuildingCategory> searchBuildingCategories =
        new HashSet<>(Arrays.stream(BuildingCategory.values()).toList());
    // Remove pathway category as we don't take them into consideration
    searchBuildingCategories.remove(BuildingCategory.PATHWAY);
    // Initialise empty vectors
    for (BuildingCategory category : searchBuildingCategories) {
      categorisedBuildings.put(category, new Vector<>());
    }
    // Split buildings into categories
    for (Building building : buildings) {
      BuildingCategory category = building.getType().getCategory();
      if (searchBuildingCategories.contains(category)) {
        categorisedBuildings.get(category).add(building);
      }
    }
    // Remove the accommodation category
    searchBuildingCategories.remove(BuildingCategory.ACCOMMODATION);

    // Check if any categories are empty, hence missing required buildings
    for (BuildingCategory category : searchBuildingCategories) {
      if (categorisedBuildings.get(category).isEmpty()) {
        // for each empty category, halve the satisfaction score
        emptyCategoryModifier *= 0.5f;
      }
    }

    // Get the maximum distance if items were placed on other sides of the map
    float mapMax = new Vector2Int(world.getWidth(), world.getHeight()).mag();

    // For every accommodation building
    for (Building accommodationBuilding :
        categorisedBuildings.get(BuildingCategory.ACCOMMODATION)) {
      // each accommodation building gets a distance score based on how close it is to other
      // building categories
      float distanceScoreTotal = 0;

      // Go through each other category of building
      for (BuildingCategory category : searchBuildingCategories) {
        float closest = mapMax;
        // Find the closest of this category of building
        for (Building building : categorisedBuildings.get(category)) {
          float distance =
              (accommodationBuilding.getPosition().subtract(building.getPosition())).mag();
          if (distance < closest) {
            closest = distance;
          }
        }
        // add a value between 0 and 1 to the distance score based on distance from category to
        // accommodation
        distanceScoreTotal += (mapMax - closest) / mapMax;
      }
      // add the normalized (0..1) score to the distanceModifier
      distanceModifier += distanceScoreTotal / searchBuildingCategories.size();
    }
    // normalize the distanceModifier so it is between 0 and 1
    distanceModifier /= categorisedBuildings.get(BuildingCategory.ACCOMMODATION).size();

    // if there are no buildings, set the distance modifier to 0
    if (searchBuildingCategories.isEmpty()
        || categorisedBuildings.get(BuildingCategory.ACCOMMODATION).isEmpty()) {
      distanceModifier = 0;
    }

    int buildingCount = gameState.getBuildingCountNoPath();

    if (buildingCount < Constants.satisfactionMinBuildingCount) {
      buildingCountModifier = (float) buildingCount / Constants.satisfactionMinBuildingCount;
    }

    HashMap<BuildingCategory, Integer> buildingCategoryCounts = new HashMap<>();
    for (BuildingType buildingType : BuildingType.values()) {
      BuildingCategory category = buildingType.getCategory();
      if (category != BuildingCategory.PATHWAY) {
        if (buildingCategoryCounts.containsKey(category)) {
          buildingCategoryCounts.put(
              category,
              buildingCategoryCounts.get(category) + gameState.getBuildingCount(buildingType));
        } else {
          buildingCategoryCounts.put(category, gameState.getBuildingCount(buildingType));
        }
      }
    }
    int greatestCategoryDifference =
        Collections.max(buildingCategoryCounts.values())
            - Collections.min(buildingCategoryCounts.values());
    if (greatestCategoryDifference > Constants.satisfactionMaxAllowedBuildingDifference) {
      buildingProportionModifier = (float) Math.max(10 - greatestCategoryDifference, 0) / 10;
    }

    emptyCategoryModifier =
        (float)
                (buildingCategoryCounts.size()
                    - Collections.frequency(buildingCategoryCounts.values(), 0))
            / buildingCategoryCounts.size();

    newSatisfactionScore =
        distanceModifier
            * buildingCountModifier
            * buildingProportionModifier
            * emptyCategoryModifier
            * gameState.satScenarioModifier;

    gameState.satDistanceModifier = distanceModifier;
    gameState.satBuildingCountModifier = buildingCountModifier;
    gameState.satBuildingProportionModifier = buildingProportionModifier;
    gameState.satEmptyCategoryModifier = emptyCategoryModifier;
    gameState.satisfactionScore = newSatisfactionScore;

    // >>>> CHANGED CODE END <<<<
  }
}
